version: '3'
services: 

  database: 
    build: ./Db
    ports: 
      - 3306:3306

  backend: 
    build: ./api
    depends_on:
      - database
    links: 
      - database
    ports:
      - 3000:3000
    
  frontend:
    build: ./web
    ports:
      - 8080:8080