# Usa la imagen oficial de Node.js
FROM node:14

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY package*.json ./
COPY index.js .

# Instala las dependencias
RUN npm install

# Comando para ejecutar la aplicación
# CMD ["node", "index.js"]
CMD ["sh", "-c", "sleep 25 && node index.js"]
