FROM node:14

WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY package*.json ./
COPY index.js .

RUN npm install

# Comando para ejecutar la aplicación
# CMD ["node", "index.js"]
CMD ["sh", "-c", "sleep 25 && node index.js"]
