name: Construyendo App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run 
        run: |
           docker compose up -d
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install 
        working-directory: ./web

      - name: Run local unit tests
        run: npm test
        working-directory: ./web

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.USUARIO}} -p ${{ secrets.CONTRA }}

      - name: tagear y push a hub
        run: |
          docker tag proyecto-backend:latest ${{ secrets.USUARIO }}/proyecto-backend:latest
          docker tag proyecto-frontend:latest ${{ secrets.USUARIO }}/proyecto-frontend:latest
          docker tag proyecto-database ${{ secrets.USUARIO }}/proyecto-database

          docker push ${{ secrets.USUARIO }}/proyecto-backend:latest
          docker push ${{ secrets.USUARIO }}/proyecto-frontend:latest
          docker push ${{ secrets.USUARIO }}/proyecto-database
  
