name: Construyendo App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run 
        run: |
           docker compose up -d
      
      - name: Install dependencies
        run: npm install 
        working-directory: ./web

      - name: Run local unit tests
        run: npm test
        working-directory: ./web

      - name: Install CodeceptJS
        run: npm install codeceptjs@3.5.13-beta.3

      - name: Update Dependencies
        run: npm update

      - name: Install Dependencies
        working-directory: ./testIntegracion
        run: |
          npm install
          npx playwright install

      - name: Run integration test
        working-directory: ./testIntegracion
        run: |
          npx codeceptjs run 

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.USUARIO}} -p ${{ secrets.CONTRA }}
        
      - name: tag push backend
        working-directory: ./api  
        run: |
          docker build -t backend . &&
          docker tag backend ${{ secrets.USUARIO }}/backend &&
          docker push ${{ secrets.USUARIO }}/backend

      - name: tag push frontend
        working-directory: ./web  
        run: |
          docker build -t frontend . &&
          docker tag frontend ${{ secrets.USUARIO }}/frontend &&
          docker push ${{ secrets.USUARIO }}/frontend

      - name: tag push database
        working-directory: ./Db 
        run: |
          docker build -t database . &&
          docker tag database ${{ secrets.USUARIO }}/database &&
          docker push ${{ secrets.USUARIO }}/database



             
     

