FROM python:3.9-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos frontend al directorio de trabajo /app
COPY index.html script.js server.py /app/

# Ejecuta el servidor web Python al iniciar el contenedor
CMD ["python", "-u", "server.py"]